name: "deploy"

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    permissions: write-all
    runs-on: "windows-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 7.x
      - name: Restore solution
        run: dotnet restore
      - name: Build solution
        run: dotnet build -c Release --no-restore
      - name: Publish solution
        run: dotnet publish -c Release --no-build --no-self-contained --runtime win-x64
      - name: Compress archive
        run: Compress-Archive -Path "OpenConnectSharp.UI/bin/Release/net7.0-windows/win-x64/publish/*" -DestinationPath "release.zip" -Force
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release.zip
          asset_name: release.zip
          asset_content_type: application/zip
