name: "deploy"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: "windows-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 7.x
      - run: dotnet restore
      - run: dotnet build -c Release --no-restore
      - run: dotnet publish -c Release --runtime win-x64
        
